apiVersion: v1
kind: Service
metadata:
  name: svc-mysql
  labels:
    app: k8s-mysql
spec:
  clusterIP: None
  selector:
    app: k8s-mysql
  ports:
    - name: tcp
      protocol: TCP
      port: 3306